services:
  - type: web
    name: spring-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/server-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://TON_HOST:5432/gestion_patients
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: 060900
      - key: SPRING_MAIL_USERNAME
        value: ayoubgrand060900@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: ton_mdp_gmail
