spring:
  datasource:
    url: jdbc:postgresql://db.tembo.com:5432/gestionnaireDePatient
    username: ayoub
    password: 060900
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ayoubgrand060900@gmail.com
    password: 060900
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  springfox:
    documentation:
      swagger-ui:
        enabled: true
        path: /swagger-ui/

server:
  port: 8081
