spring:
  datasource:
    url: jdbc:postgresql://dpg-ctit23jtq21c73duhv60-a.frankfurt-postgres.render.com:5432/gestionnaire_de_patients_db
    username: gestionnaire_de_patients_db_user
    password: cxsPPG3bjKDElIpmpN7cdVX56On4sCT5
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: clinicease4@gmail.com
    password: sxjm yeay sstn yoee
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082