spring:
  datasource:
    url: ${DATABASE_URL}           # Utilise la variable DATABASE_URL de Railway
    username: ${PGUSER}            # Utilise PGUSER pour le nom d'utilisateur (postgres)
    password: ${PGPASSWORD}        # Utilise PGPASSWORD pour le mot de passe
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update             # Change pour 'update' si tu veux éviter de créer la DB à chaque fois
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Ajouter explicitement le dialecte PostgreSQL
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ayoubgrand060900@gmail.com
    password: 060900
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  springfox:
    documentation:
      swagger-ui:
        enabled: true
        path: /swagger-ui/

server:
  port: 8081
